global:
  wizApiToken:
    clientId: ""
    secret:
      create: false
      name: wiz-api-token
wiz-kubernetes-connector:
  autoCreateConnector:
    clusterFlavor: "Kubernetes"
    connectorName: "pth-minikube"
  enabled: true
wiz-admission-controller:
  enabled: true
  replicaCount: 1
  kubernetesAuditLogsWebhook: 
    enabled: true
    replicaCount: 1
wiz-sensor:
  enabled: true
  imagePullSecret:
    create: false
    name: "sensor-image-pull"