global:
  wizApiToken:
    secret:
      create: false
      name: "wiz-api-token"
    clientId: "wgxq75hrlndpbktx3eupevf2xztxdbzfs3mvqvuu7inin4olmprgm"
    clientToken: "itvTyc1NVG5voCryQBwjoWdgAR2RKvrwyF7lDQAbzRE5qmKpKZfn63r0Bks8iy2O"
wiz-kubernetes-connector:
  autoCreateConnector:
    clusterFlavor: "Kubernetes"
    connectorName: "pth-minikube"
  enabled: true
wiz-admission-controller:
  enabled: true
  replicaCount: 1
  kubernetesAuditLogsWebhook: 
    enabled: true
    replicaCount: 1
wiz-sensor:
  enabled: true
  imagePullSecret:
    create: false
    name: "sensor-image-pull"
  wizApiToken:
    secret:
      create: false
      name: "wiz-api-token"
    clientId: "wgxq75hrlndpbktx3eupevf2xztxdbzfs3mvqvuu7inin4olmprgm"
    clientToken: "itvTyc1NVG5voCryQBwjoWdgAR2RKvrwyF7lDQAbzRE5qmKpKZfn63r0Bks8iy2O"